import {
  Controller,
  Get,
  Put,
  Patch,
  Post,
  Delete,
  Body,
  Param,
  Query,
  UseGuards,
  ParseUUIDPipe,
  HttpCode,
  HttpStatus,
} from "@nestjs/common";
import { ApiTags, ApiOperation, ApiResponse, ApiBearerAuth, ApiQuery } from "@nestjs/swagger";
import { DeliveryService } from "../service/delivery.service";
import { UpdateDeliveryDto, UpdateDeliveryStatusDto } from "../dto/update-delivery.dto";
import { DeliveryStatus } from "@fortifykitchen/types";
import { JwtAuthGuard } from "../../../common/guards/jwt-auth.guard";
import { RolesGuard } from "../../../common/guards/roles.guard";
import { Roles } from "../../../common/decorators/roles.decorator";

// Deliveries are generated by Subscriptions — there is no POST to create
// one directly here. This controller now also merges in one-off Orders
// (see /deliveries/unified and /deliveries/upcoming) so the admin
// Deliveries tab can show and group both together.
@ApiTags("delivery")
@UseGuards(JwtAuthGuard, RolesGuard)
@Roles("ADMIN", "MANAGER", "STAFF")
@ApiBearerAuth("JWT-auth")
@Controller("deliveries")
export class DeliveryController {
  constructor(private readonly deliveryService: DeliveryService) {}

  @Get()
  @ApiOperation({ summary: "Get all subscription-generated deliveries, optionally filtered by status/date" })
  @ApiQuery({ name: "status", required: false, enum: ["SCHEDULED", "PREPPING", "DELIVERED", "SKIPPED", "CANCELLED"] })
  @ApiQuery({ name: "date", required: false, type: String })
  @ApiResponse({ status: 200, description: "Returns the subscription delivery schedule." })
  async findAll(@Query("status") status?: DeliveryStatus, @Query("date") date?: string) {
    return this.deliveryService.findAll({ status, date });
  }

  @Get("unified")
  @ApiOperation({ summary: "Get one-off Orders and Subscription Deliveries merged, tagged by source" })
  @ApiQuery({ name: "date", required: false, type: String })
  @ApiResponse({ status: 200, description: "Returns the merged list, newest first." })
  async findAllUnified(@Query("date") date?: string) {
    return this.deliveryService.findAllUnified({ date });
  }

  @Get("upcoming")
  @ApiOperation({ summary: "Get upcoming (today onward) Orders + Deliveries grouped by week or month" })
  @ApiQuery({ name: "groupBy", required: false, enum: ["week", "month"] })
  @ApiResponse({ status: 200, description: "Returns grouped upcoming entries." })
  async findUpcomingGrouped(@Query("groupBy") groupBy?: "week" | "month") {
    return this.deliveryService.findUpcomingGrouped(groupBy ?? "week");
  }

  @Get("subscription/:subscriptionId")
  @ApiOperation({ summary: "Get all deliveries for one subscription" })
  @ApiResponse({ status: 200, description: "Returns that subscription's full delivery schedule." })
  async findBySubscription(@Param("subscriptionId", ParseUUIDPipe) subscriptionId: string) {
    return this.deliveryService.findBySubscription(subscriptionId);
  }

  @Get(":id")
  @ApiOperation({ summary: "Get a single delivery" })
  @ApiResponse({ status: 200, description: "Returns delivery details." })
  @ApiResponse({ status: 404, description: "Delivery not found" })
  async findOne(@Param("id", ParseUUIDPipe) id: string) {
    return this.deliveryService.findOne(id);
  }

  @Patch(":id/status")
  @ApiOperation({ summary: "Update a delivery's status (DELIVERED triggers pool deduction)" })
  @ApiResponse({ status: 200, description: "Delivery status updated." })
  async updateStatus(
    @Param("id", ParseUUIDPipe) id: string,
    @Body() dto: UpdateDeliveryStatusDto,
  ) {
    return this.deliveryService.updateStatus(id, dto.status);
  }

  @Post(":id/deliver")
  @ApiOperation({ summary: "Mark a delivery as DELIVERED and deduct the delivered grams from the subscription's pool(s)" })
  @ApiResponse({ status: 200, description: "Delivery marked delivered and pool balances updated." })
  async deliver(@Param("id", ParseUUIDPipe) id: string) {
    return this.deliveryService.markDelivered(id);
  }

  @Post(":id/postpone")
  @ApiOperation({
    summary:
      "Postpone this (and every later pending) delivery for the subscription by one interval — no deduction happens, the whole remaining schedule shifts",
  })
  @ApiResponse({ status: 200, description: "Schedule shifted." })
  async postpone(@Param("id", ParseUUIDPipe) id: string) {
    return this.deliveryService.postpone(id);
  }

  @Put(":id")
  @ApiOperation({ summary: "Update a delivery's status/notes (DELIVERED triggers pool deduction)" })
  @ApiResponse({ status: 200, description: "Delivery updated." })
  async update(@Param("id", ParseUUIDPipe) id: string, @Body() dto: UpdateDeliveryDto) {
    return this.deliveryService.update(id, dto);
  }

  @Delete(":id")
  @Roles("ADMIN", "MANAGER")
  @HttpCode(HttpStatus.NO_CONTENT)
  @ApiOperation({ summary: "Delete a single delivery occurrence" })
  @ApiResponse({ status: 204, description: "Delivery deleted." })
  async remove(@Param("id", ParseUUIDPipe) id: string): Promise<void> {
    await this.deliveryService.remove(id);
  }
}
