import { Injectable, NotFoundException, BadRequestException } from "@nestjs/common";
import { DatabaseService } from "../../../database/database.service";
import { UpdateDeliveryDto } from "../dto/update-delivery.dto";
import { Delivery, DeliveryItem, DeliveryStatus as DeliveryStatusType, UnifiedDeliveryEntry } from "@fortifykitchen/types";
import { DeliveryStatus } from "@fortifykitchen/database";
import { addDays } from "@fortifykitchen/shared";
import { parsePagination } from "../../../common/utils/pagination.util";

export interface DeliveryWithSubscriptionInfo extends Delivery {
  customerId?: string;
  customerName: string;
  packageName: string;
}

@Injectable()
export class DeliveryService {
  constructor(private readonly db: DatabaseService) {}

  // Deliveries are generated by Subscriptions (see SubscriptionsService.
  // syncUpcomingDeliveries) — there is no direct "create a delivery"
  // endpoint. This module reads/updates the schedule Subscriptions produced,
  // and (via findAllUnified/findUpcoming) merges in one-off Orders so the
  // admin Deliveries tab can show/group everything together.
  async findAll(filters?: { status?: DeliveryStatusType; date?: string }): Promise<DeliveryWithSubscriptionInfo[]> {
    const deliveries = await this.db.client.delivery.findMany({
      where: {
        status: filters?.status,
        scheduledDate: filters?.date ? new Date(filters.date) : undefined,
      },
      include: {
        items: true,
        subscription: { select: { customerId: true, customerName: true, packageName: true } },
      },
      orderBy: { scheduledDate: "asc" },
    });

    return deliveries.map((d) => this.mapDelivery(d));
  }

  // Merges one-off Orders and Subscription-generated Deliveries into a
  // single list tagged by `source`, so the admin Deliveries tab can
  // distinguish between them (requirement: "identify between subscription
  // and normal delivery") while still showing them together.
  async findAllUnified(filters?: { date?: string; page?: string; limit?: string }): Promise<UnifiedDeliveryEntry[]> {
    const dateFilter = filters?.date ? new Date(filters.date) : undefined;

    const [orders, deliveries] = await Promise.all([
      this.db.client.order.findMany({
        where: dateFilter ? { deliveryDate: dateFilter } : undefined,
        include: { items: true },
        orderBy: { deliveryDate: "asc" },
      }),
      this.db.client.delivery.findMany({
        where: dateFilter ? { scheduledDate: dateFilter } : undefined,
        include: {
          items: true,
          subscription: { select: { customerId: true, customerName: true, packageName: true } },
        },
        orderBy: { scheduledDate: "asc" },
      }),
    ]);

    const fromOrders: UnifiedDeliveryEntry[] = orders.map((o) => ({
      id: o.id,
      source: "ORDER",
      scheduledDate: o.deliveryDate,
      status: o.deliveryStatus as DeliveryStatusType,
      customerId: o.customerId ?? undefined,
      customerName: o.customerName,
      items: o.items.map((i) => ({ protein: i.protein as DeliveryItem["protein"], flavor: i.flavor, sizeGrams: i.sizeGrams, qty: i.qty })),
      totalGrams: o.items.reduce((s, i) => s + i.qty * i.sizeGrams, 0),
    }));

    const fromDeliveries: UnifiedDeliveryEntry[] = deliveries.map((d) => ({
      id: d.id,
      source: "SUBSCRIPTION",
      scheduledDate: d.scheduledDate,
      status: d.status as DeliveryStatusType,
      customerId: d.subscription.customerId ?? undefined,
      customerName: d.subscription.customerName,
      subscriptionId: d.subscriptionId,
      packageName: d.subscription.packageName,
      items: d.items.map((i) => ({ protein: i.protein as DeliveryItem["protein"], flavor: i.flavor, sizeGrams: i.sizeGrams, qty: i.qty })),
      totalGrams: d.items.reduce((s, i) => s + i.qty * i.sizeGrams, 0),
    }));

    // Oldest first — matches the admin Deliveries tab's "Tất cả" view,
    // which shows day groups oldest-to-newest for easier chronological
    // monitoring.
    const merged = [...fromOrders, ...fromDeliveries].sort(
      (a, b) => new Date(a.scheduledDate).getTime() - new Date(b.scheduledDate).getTime(),
    );

    // Pagination applies as a post-merge slice (there's no way to push
    // skip/take down into two separate findMany calls that then get
    // interleaved by date) — opt-in only, since the admin Deliveries tab's
    // day-grouping view needs the full unfiltered set to group correctly and
    // never passes page/limit today.
    const { skip, take } = parsePagination(filters?.page, filters?.limit);
    if (skip === undefined || take === undefined) return merged;
    return merged.slice(skip, skip + take);
  }

  // Upcoming (today onward) entries grouped by day, ISO week, or month, for
  // the "see upcoming deliveries for both normal and subscription orders,
  // grouped into day/week/month" requirement. Day grouping mirrors the same
  // calendar-day bucketing the "Tất cả" tab uses client-side, so switching
  // grouping granularity doesn't change what a "day" means.
  async findUpcomingGrouped(groupBy: "day" | "week" | "month" = "week") {
    const today = new Date();
    today.setHours(0, 0, 0, 0);

    const all = await this.findAllUnified();
    const upcoming = all
      .filter((e) => new Date(e.scheduledDate) >= today && e.status !== "CANCELLED" && e.status !== "DELIVERED")
      .sort((a, b) => new Date(a.scheduledDate).getTime() - new Date(b.scheduledDate).getTime());

    const groups = new Map<string, UnifiedDeliveryEntry[]>();
    for (const entry of upcoming) {
      const d = new Date(entry.scheduledDate);
      let key: string;
      if (groupBy === "day") {
        key = `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, "0")}-${String(d.getDate()).padStart(2, "0")}`;
      } else if (groupBy === "month") {
        key = `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, "0")}`;
      } else {
        // ISO-ish week key: year + week number (Mon-start)
        const dayNum = (d.getDay() + 6) % 7;
        const thursday = new Date(d);
        thursday.setDate(d.getDate() - dayNum + 3);
        const firstThursday = new Date(thursday.getFullYear(), 0, 4);
        const weekNum =
          1 + Math.round(((thursday.getTime() - firstThursday.getTime()) / 86400000 - 3 + ((firstThursday.getDay() + 6) % 7)) / 7);
        key = `${thursday.getFullYear()}-W${String(weekNum).padStart(2, "0")}`;
      }
      if (!groups.has(key)) groups.set(key, []);
      groups.get(key)!.push(entry);
    }

    return Array.from(groups.entries()).map(([key, entries]) => ({
      key,
      count: entries.length,
      totalGrams: entries.reduce((s, e) => s + e.totalGrams, 0),
      entries,
    }));
  }

  async findOne(id: string): Promise<DeliveryWithSubscriptionInfo> {
    const delivery = await this.db.client.delivery.findUnique({
      where: { id },
      include: {
        items: true,
        subscription: { select: { customerId: true, customerName: true, packageName: true } },
      },
    });

    if (!delivery) {
      throw new NotFoundException(`Delivery with ID ${id} not found`);
    }

    return this.mapDelivery(delivery);
  }

  async findBySubscription(subscriptionId: string): Promise<DeliveryWithSubscriptionInfo[]> {
    const deliveries = await this.db.client.delivery.findMany({
      where: { subscriptionId },
      include: {
        items: true,
        subscription: { select: { customerId: true, customerName: true, packageName: true } },
      },
      orderBy: { scheduledDate: "asc" },
    });

    return deliveries.map((d) => this.mapDelivery(d));
  }

  async updateStatus(id: string, status: DeliveryStatus): Promise<DeliveryWithSubscriptionInfo> {
    // Marking DELIVERED must go through markDelivered so the pool deduction
    // actually happens — routing it here too keeps the simple status-only
    // endpoint from silently skipping requirement #5's balance integrity.
    if (status === "DELIVERED") {
      return this.markDelivered(id);
    }
    await this.findOne(id);
    const delivery = await this.db.client.delivery.update({
      where: { id },
      data: { status },
      include: {
        items: true,
        subscription: { select: { customerId: true, customerName: true, packageName: true } },
      },
    });
    return this.mapDelivery(delivery);
  }

  async update(id: string, dto: UpdateDeliveryDto): Promise<DeliveryWithSubscriptionInfo> {
    if (dto.status === "DELIVERED") {
      return this.markDelivered(id, dto.notes);
    }
    await this.findOne(id);
    const delivery = await this.db.client.delivery.update({
      where: { id },
      data: { status: dto.status, notes: dto.notes },
      include: {
        items: true,
        subscription: { select: { customerId: true, customerName: true, packageName: true } },
      },
    });
    return this.mapDelivery(delivery);
  }

  // Marks a delivery DELIVERED and, in the same transaction, deducts the
  // actual delivered grams from each matching protein pool. Idempotent —
  // calling this on an already-DELIVERED delivery is a no-op rather than
  // double-deducting, protecting the integrity requirement even against
  // duplicate/retried requests.
  async markDelivered(id: string, notes?: string): Promise<DeliveryWithSubscriptionInfo> {
    const delivery = await this.db.client.delivery.findUnique({
      where: { id },
      include: { items: true, subscription: { include: { pools: true } } },
    });
    if (!delivery) {
      throw new NotFoundException(`Delivery with ID ${id} not found`);
    }
    if (delivery.status === "DELIVERED") {
      return this.findOne(id);
    }
    if (delivery.status === "CANCELLED") {
      throw new BadRequestException("Không thể xác nhận giao hàng cho một đơn đã bị hủy");
    }

    const gramsByProtein: Record<string, number> = {};
    for (const item of delivery.items) {
      gramsByProtein[item.protein] = (gramsByProtein[item.protein] ?? 0) + item.qty * item.sizeGrams;
    }

    await this.db.client.$transaction(async (tx) => {
      for (const pool of delivery.subscription.pools) {
        const deduction = gramsByProtein[pool.protein];
        if (!deduction) continue;
        await tx.subscriptionPool.update({
          where: { id: pool.id },
          data: { remainingGrams: Math.max(0, pool.remainingGrams - deduction) },
        });
      }
      await tx.delivery.update({
        where: { id },
        data: { status: "DELIVERED", notes: notes ?? delivery.notes },
      });

      // If every pool is fully consumed, close out the subscription.
      const refreshedPools = await tx.subscriptionPool.findMany({ where: { subscriptionId: delivery.subscriptionId } });
      const allDepleted = refreshedPools.every((p) => p.remainingGrams <= 0);
      if (allDepleted) {
        await tx.subscription.update({ where: { id: delivery.subscriptionId }, data: { status: "COMPLETED" } });
      }
    });

    return this.findOne(id);
  }

  // Postpones today's (or any not-yet-delivered) occurrence — the
  // conserve-for-later requirement: no deduction happens (deduction only
  // ever happens in markDelivered), and rather than leaving a gap, the
  // WHOLE remaining schedule for that subscription shifts forward by one
  // delivery interval so spacing between occurrences stays consistent.
  async postpone(id: string): Promise<DeliveryWithSubscriptionInfo> {
    const delivery = await this.db.client.delivery.findUnique({
      where: { id },
      include: { subscription: true },
    });
    if (!delivery) {
      throw new NotFoundException(`Delivery with ID ${id} not found`);
    }
    if (delivery.status === "DELIVERED" || delivery.status === "CANCELLED") {
      throw new BadRequestException("Chỉ có thể hoãn các đơn đang chờ giao hoặc đang chuẩn bị");
    }

    const interval = delivery.subscription.deliveryIntervalDays;
    const affected = await this.db.client.delivery.findMany({
      where: {
        subscriptionId: delivery.subscriptionId,
        scheduledDate: { gte: delivery.scheduledDate },
        status: { in: ["SCHEDULED", "PREPPING"] },
      },
      orderBy: { scheduledDate: "asc" },
    });

    await this.db.client.$transaction(async (tx) => {
      for (const d of affected) {
        const newDate = addDays(d.scheduledDate, interval);
        const noteLine = `Hoãn từ ${d.scheduledDate.toISOString().split("T")[0]} sang ${newDate.toISOString().split("T")[0]}`;
        await tx.delivery.update({
          where: { id: d.id },
          data: {
            scheduledDate: newDate,
            notes: d.notes ? `${d.notes}\n${noteLine}` : noteLine,
          },
        });
      }
      await tx.subscription.update({
        where: { id: delivery.subscriptionId },
        data: { postponedCount: { increment: 1 } },
      });
    });

    return this.findOne(id);
  }

  // Deleting a delivery just removes that one occurrence — the subscription
  // and its remaining deliveries are untouched.
  async remove(id: string): Promise<void> {
    await this.findOne(id);
    await this.db.client.delivery.delete({ where: { id } });
  }

  private mapDelivery(delivery: {
    id: string;
    subscriptionId: string;
    scheduledDate: Date;
    status: string;
    notes: string | null;
    subscription: { customerId: string | null; customerName: string; packageName: string };
    items: Array<{
      id: string;
      deliveryId: string;
      menuItemId: string | null;
      protein: string;
      flavor: string;
      sizeGrams: number;
      unitPrice: number;
      qty: number;
    }>;
    createdAt: Date;
    updatedAt: Date;
  }): DeliveryWithSubscriptionInfo {
    return {
      id: delivery.id,
      subscriptionId: delivery.subscriptionId,
      scheduledDate: delivery.scheduledDate,
      status: delivery.status as Delivery["status"],
      notes: delivery.notes ?? undefined,
      customerId: delivery.subscription.customerId ?? undefined,
      customerName: delivery.subscription.customerName,
      packageName: delivery.subscription.packageName,
      items: delivery.items.map(
        (i): DeliveryItem => ({
          id: i.id,
          deliveryId: i.deliveryId,
          menuItemId: i.menuItemId ?? undefined,
          protein: i.protein as DeliveryItem["protein"],
          flavor: i.flavor,
          sizeGrams: i.sizeGrams,
          unitPrice: i.unitPrice,
          qty: i.qty,
        }),
      ),
      createdAt: delivery.createdAt,
      updatedAt: delivery.updatedAt,
    };
  }
}
