export type UserRole = "ADMIN" | "MANAGER" | "STAFF" | "CUSTOMER";

export interface User {
  id: string;
  email: string;
  firstName: string;
  lastName: string;
  role: UserRole;
  isActive: boolean;
  createdAt: Date;
  updatedAt: Date;
}

// Customer is intentionally independent of User — there is no customer
// self-serve login today, staff track customers by name/phone/Zalo only.
// userId is optional so a customer portal can be added later.
export interface Customer {
  id: string;
  userId?: string;
  name: string;
  phone?: string;
  zalo?: string;
  address?: string;
  notes?: string;
  createdAt: Date;
  updatedAt: Date;
}

export type Protein = "CHICKEN" | "BEEF" | "SHRIMP";

export interface Category {
  id: string;
  name: string;
  description?: string;
  slug: string;
  createdAt: Date;
  updatedAt: Date;
}

// A sellable SKU: one protein + flavor + portion size combination
// (e.g. chicken / xá xíu / 150g). price is in whole VND (no subunit).
export interface MenuItem {
  id: string;
  protein: Protein;
  flavor: string;
  sizeGrams: number;
  price: number;
  isAvailable: boolean;
  categoryId?: string;
  // Optional customer-facing copy/photo — not used by the admin tool today
  // but needed by the customer-web storefront.
  description?: string;
  imageUrl?: string;
  // Portions prepped and ready right now — 0 means "needs prep" for this
  // SKU. Decremented when an Order using it is fulfilled IMMEDIATE.
  stockQuantity: number;
  createdAt: Date;
  updatedAt: Date;
}

// The shape the pricing engine (packages/shared/pricing.ts) operates on —
// shared by Order line items, Subscription per-delivery item templates, and
// Delivery item snapshots. Carrying protein/flavor/sizeGrams/unitPrice as a
// snapshot (rather than just a menuItemId reference) protects historical
// records from later menu changes.
export interface LineItem {
  menuItemId?: string;
  protein: Protein;
  flavor: string;
  sizeGrams: number;
  unitPrice: number;
  qty: number;
}

// Payment state as tracked by staff for an Order or Subscription — mirrors
// the original 3-step Vietnamese flow (Chưa thanh toán / Đã cọc / Đã thanh
// toán). See PAYMENT_STATE_LABELS in packages/shared for display strings.
export type PaymentState = "UNPAID" | "DEPOSIT" | "PAID";

// Fulfillment status of a single delivery occurrence — used on both Order
// (a one-off order is itself a single delivery day) and Delivery (each
// occurrence generated by a Subscription's schedule).
export type DeliveryStatus =
  | "SCHEDULED"
  | "PREPPING"
  | "DELIVERED"
  | "SKIPPED"
  | "CANCELLED";

export interface OrderItem extends LineItem {
  id: string;
  orderId: string;
}

// Whether an Order was fulfilled from ready-made stock (no prep needed) or
// needs the kitchen to prep it first. Computed server-side at order-creation
// time from each line item's MenuItem.stockQuantity — never client-set.
export type OrderFulfillmentType = "IMMEDIATE" | "SCHEDULED";

export interface Order {
  id: string;
  customerId?: string;
  customerName: string;
  deliveryDate: Date;
  paymentStatus: PaymentState;
  deliveryStatus: DeliveryStatus;
  fulfillmentType: OrderFulfillmentType;
  subtotal: number;
  discountAmount: number;
  total: number;
  notes?: string;
  items: OrderItem[];
  createdAt: Date;
  updatedAt: Date;
}

export type SubscriptionStatus = "ACTIVE" | "PAUSED" | "COMPLETED" | "CANCELLED";

// One protein's purchased balance within a volume subscription (e.g. "30kg
// CHICKEN, 12.4kg remaining"). remainingGrams only decreases when a
// Delivery containing items of this protein is marked DELIVERED.
export interface SubscriptionPool {
  id: string;
  subscriptionId: string;
  protein: Protein;
  totalGrams: number;
  remainingGrams: number;
  createdAt: Date;
  updatedAt: Date;
}

// Volume-based subscription: the customer buys a total weight per protein
// up front (see pools), then separately picks a delivery cadence
// (deliveryAmountGrams delivered every deliveryIntervalDays). The specific
// flavor for each occurrence is chosen closer to delivery time (see
// Delivery/DeliveryItem) and only deducted from the matching pool once
// that delivery is actually marked DELIVERED.
export interface Subscription {
  id: string;
  customerId?: string;
  customerName: string;
  packageName: string;
  totalGrams: number;
  deliveryAmountGrams: number;
  deliveryIntervalDays: number;
  startDate: Date;
  totalPrice: number;
  paymentStatus: PaymentState;
  status: SubscriptionStatus;
  postponedCount: number;
  pools: SubscriptionPool[];
  createdAt: Date;
  updatedAt: Date;
}

export interface DeliveryItem extends LineItem {
  id: string;
  deliveryId: string;
}

// One occurrence of a subscription's volume delivery schedule. Items are
// materialized at generation time (see SubscriptionsService.
// syncUpcomingDeliveries) with a default flavor per protein, which can be
// edited any time before the delivery is marked DELIVERED.
export interface Delivery {
  id: string;
  subscriptionId: string;
  scheduledDate: Date;
  status: DeliveryStatus;
  notes?: string;
  items: DeliveryItem[];
  createdAt: Date;
  updatedAt: Date;
}

// Unified shape returned by GET /delivery for the admin Deliveries tab,
// merging one-off Orders and Subscription-generated Deliveries into a
// single list tagged by source so the UI can distinguish and group them.
export interface UnifiedDeliveryEntry {
  id: string;
  source: "ORDER" | "SUBSCRIPTION";
  scheduledDate: Date;
  status: DeliveryStatus;
  customerId?: string;
  customerName: string;
  subscriptionId?: string;
  packageName?: string;
  items: { protein: Protein; flavor: string; sizeGrams: number; qty: number }[];
  totalGrams: number;
}

// Ledger of actual payment transactions (future real payment processing) —
// distinct from Order.paymentStatus / Subscription.paymentStatus above,
// which are the simple staff-tracked status shown in the UI today.
export type PaymentMethod =
  | "CREDIT_CARD"
  | "DEBIT_CARD"
  | "PAYPAL"
  | "STRIPE"
  | "CASH_ON_DELIVERY";

export type PaymentStatus = "PENDING" | "COMPLETED" | "FAILED" | "REFUNDED";

export interface Payment {
  id: string;
  orderId?: string;
  subscriptionId?: string;
  amount: number;
  method: PaymentMethod;
  status: PaymentStatus;
  transactionId?: string;
  createdAt: Date;
  updatedAt: Date;
}
